team_red: ["jnogueira", "tmadeira", "talmeida", "jmoreira"]
team_green: ["ttavares","acastro","dsilva", "psilva"]
team_blue: ["moliveira","jsantos","drato","mferreira"]
#team_red: ["tmadeira"]
#team_green: ["ttavares"]
#team_blue: ["moliveira"]
hunting_distance: 0.5
game_duration: 60
immunity_duration: 3
killed_duration: 6
positive_score: 1
negative_score: -1