team_red: ["jnogueira", "tmadeira", "talmeida", "jmoreira"]
team_green: ["ttavares","acastro","dsilva", "psilva"]
team_blue: ["moliveira","jsantos","drato","mferreira"]
hunting_distance: 0.5
game_duration: 120
positive_score: 1
negative_score: -1